[project]
name = "timelock-init"
authors = ["TimeInit Team"]
description = "A smart contract verification platform focusing on timelock mechanisms"
telemetry = false
requirements = []
[contracts.timelock-verification]
path = "contracts/timelock-verification.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
